config/routes.rb
Rails.application.routes.draw do
  get 'quotes/rails'

  get 'quotes/generate'

  get 'quotes/controller'

  get 'quotes/home'

  get 'quotes/index'

	root "home#index"
	post '/games/create', to: 'games#create', as: 'create_game'
	post '/games/save', to: 'games#save', as: 'save_game'
	resources :characters, only: [:index, :show]
	resources :games, only: [:index, :show]
	resources :quotes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
	has_many :game_logs
  has_many :games, through: :game_logs
	has_many :quotes
	validates :name, :description, :img, presence: true

end

app/models/game.rb
class Game < ApplicationRecord
	has_many :game_logs
  has_many :characters, through: :game_logs
	has_many :quotes, through: :characters
	serialize :ten_quote_ids, Array
  serialize :state, Array

	def game_quotes
    if ten_quote_ids.length == 10
      quotes.where(id: ten_quote_ids)
    else
      ten_quotes = quotes.order('RANDOM()').limit(10)
      update ten_quote_ids: ten_quotes.map(&:id)
      ten_quotes
    end
  end
end

app/models/game_character.rb
class GameCharacter < ApplicationRecord
	belongs_to :game
  belongs_to :character
end

app/models/game_log.rb
class GameLog < ApplicationRecord
	belongs_to :game
  belongs_to :character
end

app/models/quote.rb
class Quote < ApplicationRecord
	belongs_to :character
	validates :content, :source, :character_id, presence: true
	after_save :save_character_name

	def save_character_name
    if character_name == nil
      name = character.name
			update character_name: name
    end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

	def index
		@characters = Character.all
		render json: @characters
	end

	def show
		@character = Character.find(params[:id])
		render json: @character
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def create
		@game = Game.create(difficulty_params)
		character_params.each do |character|
			@game.characters << Character.find_by(character_params[character])
		end
    render json: @game, status: 201
	end

	def save
		@game = Game.find(postgame_params[:id])
		@game.update(state: postgame_params[:state], completed: true)
	end

	def index
		@games = Game.all
		render json: @games
	end

	def show
		@game = Game.find(params[:id])
		render json: @game
	end

	private

	def character_params
		params.require(:characters).permit!
	end

	def difficulty_params
		params.permit(:difficulty)
	end

	def postgame_params
		params.permit(:id, :state => [])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@characters = Character.all.order('name ASC')
	end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quotes = Quote.all
    render json: @quotes
  end

  def show
    @quote = Quote.find(params[:id])
    render json: @quote
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
	def svg(name)
	  file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
	  return File.read(file_path).html_safe if File.exists?(file_path)
	  '(not found)'
	end
end

app/helpers/svg_helper.rb
module SvgHelper
	def svg(name)
	  file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
	  return File.read(file_path).html_safe if File.exists?(file_path)
	  '(not found)'
	end
end

app/views/application/_footer.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/application/_handlebars.html.erb
<script id="game-picture-template" type="text/x-handlebars-template">
  <div id="gamecard-container">
    {{#each this}}
  		<div class="gamecard" data-id="{{id}}" data-name="{{name}}">
  		  <img id="selected-character-{{@index}}">
  		  <div class="text-container center">
  		    <h5>{{name}}</h5>
  		  </div>
  		</div>
  	{{/each}}
  </div>
</script>

<script id="game-quote-template" type="text/x-handlebars-template">
    <h6 class="center">Quote {{counter}}/10</h6>
    <p>"{{content}}"</p>
</script>

app/views/application/_head.html.erb
<head>
  <title>Who Said It?</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Search Engine -->
  <meta name="description" content="The Game of Deciding Who Said What! Choose up to four characters for up to 495 different possible quote combinations. App built by Joel Hoelting, joelhoelting.com" />

  <!-- Schema.org (Google) -->
  <meta itemprop="name" content="Who Said It?" />
  <meta itemprop="description" content="The Game of Deciding Who Said What! Choose up to four characters from a pool of twelve characters for up to 495 different possible quote combinations." />

  <!-- Open Graph (Facebook, Pinterest & Google+) -->
  <meta name="og:title" content="Who Said It?" />
  <meta name="og:description" content="The Game of Deciding Who Said What! Choose up to four characters from a pool of twelve characters for up to 495 different possible quote combinations." />
  <meta name="og:url" content="http://whosaidit.co" />
  <meta name="og:site_name" content="Who Said It?" />
  <meta name="og:locale" content="en_US" />
  <meta name="og:type" content="website" />

  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway|Merriweather', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-97675920-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());

    gtag('config', 'UA-97675920-2');
  </script>

</head>

app/views/home/index.html.erb
<%= render 'sections/welcome_screen' %>
<%= render 'sections/character_screen' %>
<%= render 'sections/game_screen' %>
<%= render 'sections/postgame_screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'head' %>
  <body>
    <div class="container">
      <%= render 'components/loader' %>
      <%= yield %>
      <%= render 'footer' %>
      <%= render 'handlebars' %>
    </div>
  </body>
</html>

app/views/sections/_character_screen.html.erb
<div id="character-screen" class="hide">
	<%=image_tag("logos/character_screen_logo.png", :class => "logo") %>
	<div id="difficulty" class="center">
		<button id="easy" data-max-characters="2" class="active">Easy</button>
		<button id="medium" data-max-characters="3">Medium</button>
		<button id="hard" data-max-characters="4">Hard</button>
	</div>
	<%= form_tag(create_game_path, method: 'post', id: 'create-game') do %>
	  <% @characters.each_slice(4) do |slice| %>
		  <div class="row">
			<% slice.each do |character| %>
			  <%= render partial: 'components/flipcard', locals: { object: character } %>
			<% end %>
		  </div>
		<% end %>
	  <button type="submit">Start Game</button>
	<% end %>
	<%= render 'components/charactermodal' %>
</div>

app/views/sections/_character_select.html.erb
<div id="character-select" class="hide">
	<%= form_tag(create_game_path, method: 'post', id: 'create-game') do %>
	  <div class="row">
	     <h1 class="cs-title">Character Selection</h1>
	  </div>
	  <% @characters.each_slice(4) do |slice| %>
		  <div class="row">
		    <% slice.each do |character| %>
		      <%= render partial: 'components/card', locals: { object: character } %>
		    <% end %>
		  </div>
		<% end %>
	  <button type="submit">Start Game</button>
	<% end %>
</div>

app/views/sections/_game_screen.html.erb
<div id="game-screen" class="hide">
  <%=image_tag("logos/who_said_it_logo.png", :class => "logo") %>
  <div id="game-pictures">
  </div>
  <div id="game-quotes">
  </div>
  <%= render 'components/gamemodal' %>
</div>

app/views/sections/_postgame_screen.html.erb
<div id="postgame-screen" class="hide center">
	<h3 id="score"></h3>
	<%= render 'components/scoremeter' %>
	<button id="play-again" >Play Again</button>
</div>

app/views/sections/_welcome.html.erb
<div id="welcome">
  <%= svg 'who_said_it' %>
	<h4 id="subtitle">The Game of Deciding Who Said What</h3>
	<button id="play-game">Play Game</button>
</div>

app/views/sections/_welcome_screen.html.erb
<div id="welcome-screen">
    <%= svg 'logos/who_said_it_title' %>
  	<h5 id="subtitle">The Game of Deciding Who Said What</h5>
  	<button id="play">Play Game</button>
    <p id="games-played"><%= Game.all.count =%> Games Played!</p>
</div>